# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - stockfish-gui

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'  # Changed to a more stable Node.js version

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present

      - name: Create zip archive
        run: |
          if [ -f "node-app.zip" ]; then
            rm node-app.zip  # Remove existing archive if it exists
          fi
          zip -r node-app.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: node-app.zip  # Upload the zip archive instead of individual files

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Clean up temp folders
        run: |
          if [ -d "${RUNNER_TEMP}/zipdeploy" ]; then
            rm -rf "${RUNNER_TEMP}/zipdeploy"
          fi
          
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'stockfish-gui'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_6A5550D662DF4C1A93EDEE32FE8C7D87 }}
          package: ${{ github.workspace }}/node-app.zip  # Deploy the contents of the zip archive
